package AnyPackageName.om;

/**
 * The skeleton for this class was autogenerated by Torque on:
 *
 * [Sun Jun 16 04:08:04 PDT 2019]
 *
 *  You should add additional methods to this class to meet the
 *  application requirements.  This class will only be generated as
 *  long as it does not already exist in the output directory.
 */
public class TurbineUserPeer
    extends AnyPackageName.om.BaseTurbineUserPeer
{
    /** Serial version */
    private static final long serialVersionUID = 1560683284976L;

}
